version: '3'
networks:
    all:
      driver: bridge
services:
  security:
    build: ./SportApp_SeguridadService
    ports:
      - "3000:5000"
    environment:
      DB_NAME: users
      DB_HOST: databases
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      databases:
        condition: service_healthy
    networks:
      - all
  databases:
      build: ./data_bases
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 2s
        timeout: 5s
        retries: 5
      networks:
        - all
  